
platform_url = 'https://platformxxx.risksense.com'                             
#your platform URL
api_key=""                                    
#API key of the user in the platform
client_id=123                                   
#client id
connector_name=""                             
#name of the connector you want to provide
networkId=123                              
#network to which you want to ingest the assets
fortify_username=""  
fortify_password=""                        
#username and password of fortify on demand
createAssetsIfZeroVulnFoundInFile=true        
#whether to create assets if 0 vuln is there
connector_url=""                              
# url of the connector
schedule_enabled=true                         
#whether to enable schedule
schedule_type="DAILY"                         
#whether daily monthly or weekly
hourOfDay=3                                   
#hour of the day
autoUrba=true
#whether to enable auto urba
slcstatuschoice="SELECTED"  
#slc status choice can either be "SELECTED" or "ALL"
